### ISSUE TITLE
When Stop container and restart the instalations begins again

### ISSUE THREAD

**Issue by csalazart** [yobasystems/alpine-prestashop#2]
Thanks for this repo i apreciate it alot helpme with my RPI, server DEVs
when i stop the container with PS, and start again its beings a instalation process again, and the admin folder change the name, again.. and fail on backend .. i need to stop recreate the container and start with the enviroment PS_INSTALL = 0 ..

And how can do with the user inside the container? becasue the permissions folder its diferentes to the users outside the container and its dificults to get write/edit  permissions on it!

**Comment by dominictayloruk** [comment]
You have to set the env variables

```
    ENV REPO="https://github.com/PrestaShop/PrestaShop" \
    SSH_PRIVATE_KEY="" \
    URL="www.example.co.uk" \
    PS_FOLDER_ADMIN="admin" \
    PS_FOLDER_INSTALL="install" \
    PS_INSTALL_AUTO="0" \
    PS_ERASE_DB="0" \
    PS_INSTALL_GIT="0" \
    CLOUDFLARE_CDN="0" \
    DEV_MODE="0" \
    TERM="xterm" \
    MYSQL_HOST="172.17.0.1" \
    MYSQL_DATABASE="" \
    MYSQL_USER="" \
    MYSQL_PASSWORD=""
```

So after you have installed a fresh installation stop the container and edit PS INSTALL AUTO to 0. You also need to edit the admin folder location to whatever it renamed for you after installation.

In terms of storage i'm not sure if it would work from a samba share as i use NFS or iSCSI for k8s storage. I think you may need to set the correct permissions on the server.

You could try running this inside the prestashop container
```
find /usr/html/ -type f -exec chmod 644 {} \; && find /usr/html/ -type d -exec chmod 755 {} \;

chown -R nginx:nginx /usr/html/
```

**Comment by csalazart** [comment]
Thansk i do that for the enviroments i use YML with portainer its works ..
but on install done i stop the container change the enviroment and restart again for the container..
and permissions i add users:group to my groups locals, but i like to have some way to set the user, or UID/GID from host to guest , automatic, 

im usign a samba server on RPI, to share folder on networks and use on my windows pc (yes i know win but its so), i change the settins to 775 add the users show in folder "weir users:group" to samba gruop and main user.

its not automatic sure buts its okey!!

**Comment by dominictayloruk** [comment]
Not sure on SMB shares, they usually never really work as intended. You would be better off using NFS or iSCSI
