### ISSUE TITLE
Don't charge index.html or index.php automaticly

### ISSUE THREAD

**Issue by ManjiChiba** [yobasystems/alpine-prestashop#3]
I already start the container, but, I only can charge index.html if I put http://keysagogo.duckdns.org/index.html

if I put only http://keysagogo.duckdns.org it fails with error

403 Forbidden
nginx/1.14.2

Sorry, for my poor english.

**Comment by dominictayloruk** [comment]
Try running the following command in the container;

```
chown -R nginx:nginx /usr/html
```

**Comment by ManjiChiba** [comment]
> Try running the following command in the container;
> 
> ```
> chown -R nginx:nginx /usr/html
> ```

I went to the container (from portainer) and I saw how was the rights:

bash-4.4# ls -la
total 16
drwxr-xr-x    2 nginx    nginx         4096 Jun  8 19:51 .
drwxr-xr-x    1 root     root          4096 Jun  8 19:53 ..
-rw-r--r--    1 nginx    nginx          120 May  8 19:02 index.html
-rw-r--r--    1 nginx    nginx           20 Apr 15 19:26 info.php
bash-4.4# 

but... I did it

same result, nothing change.

**Comment by ManjiChiba** [comment]
I see this strange message on Portainer log of the container.

[i] /usr/html directory already contains files, making nginx the owner...
[i] Pretashop already installed...
[i] Pretashop already installed...
[i] Changing admin directory...
[i] Changing server name...
[i] Not behind Cloudflare...
[i] Not in Dev Mode, Production Mode...
[i] Fixing permissions & ownership...
 Starting Prestashop...
2021/06/08 19:53:04 [notice] 22#22: using the "epoll" event method
2021/06/08 19:53:04 [notice] 22#22: nginx/1.14.2
2021/06/08 19:53:04 [notice] 22#22: OS: Linux 5.10.17-v7+
2021/06/08 19:53:04 [notice] 22#22: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2021/06/08 19:53:04 [notice] 22#22: start worker processes
2021/06/08 19:53:04 [notice] 22#22: start worker process 23
2021/06/08 19:54:42 [error] 23#23: *2 directory index of "/usr/html/" is forbidden, client: 90.94.186.127, server: www.example.co.uk, request: "GET / HTTP/1.1", host: "keysagogo.duckdns.org"

Stranged I see the content of the files:

/etc/nginx.conf

and see this lines


server {
    charset utf-8;
    listen 80;
    server_name www.example.co.uk;
    root        /usr/html;
    index       index.php;


Maybe the problem are on ser_name parameter or index parameter?


I already see this on file /etc/nginx/conf.d/default.conf

server {
        listen 80 default_server;
        listen [::]:80 default_server;
        # Everything is a 404
        location / {
                return 404;
        }
        # You may need this to prevent return 404 recursion.
        location = /404.html {
                internal;
        }
}

Maybe need some lines here than...

server {
        listen 80 default_server;
		**index index.php index.html**;	        
        listen [::]:80 default_server;

        Everything is a 404
        location / {
				**index index.php index.html**
                #return 404;
        }

        You may need this to prevent return 404 recursion.
        location = /404.html {
                internal;
        }
}

**Comment by dominictayloruk** [comment]
Try changing the env var in portainer ;

```VIRTUAL_HOST: example.co.uk ```

to 

```VIRTUAL_HOST: keysagogo.duckdns.org```

**Comment by dominictayloruk** [comment]
Also the container doesn't have permission on the host to change the ownership of the files. Maybe you need to chmod your host directory to allow the container to write.
